### PR TITLE
Distribution Graph

### PR DESCRIPTION
**Pull request by micksab**
https://youtu.be/l-1rxEM8ibE

Addition of new graph type that displays the distribution of time taken for requests to be served by one or more URLs

Features include:
*Display of distribution for one or more URLs at the same graph
*Ability to modify core settings of the graph by right-clicking on it and selection option "Distribution Graph Settings"
 -- Customize graph Title
 -- (Optional) Display statistics about the URLs included in the graph
 -- Ability to define the class size (bin size) used to group response times
 -- Ability to define min and max values included in the graph (x-axis)
 -- Ability to enable/disable smoothing of graph and the relevant tension used.

### CODE REVIEW

**Comment by RickStrahl** [comment]
Thanks @micksab. I'll take a look but it'll be a bit - looks there's quite a bit here to review.

**Comment by RickStrahl** [comment]
Sorry for the delay getting back on this. Since some time has passed there are a couple of merge errors in the form. Can you see if you can resolve those and I'll take a look at the code to see if this can be merged smoothly.

Those are very good enhancements - certainly something beyond of what I would have ever added, so this is great.

**Comment by micksab** [comment]
Sure, I'll take a look during the weekend and let you know when I'm done.

**Comment by RickStrahl** [comment]
Thanks.

**Pull request closed without merging**
